### ISSUE TITLE
TypeError: SeqFeature.__init__() got an unexpected keyword argument 'strand'

### ISSUE THREAD

**Issue by comingkms** [nikolaichik/SigmoID#43]
Hi,
I have an issue to run your pipeline. I tried HmmGen and  TermGen  and got very similar errors ? 

Running the HmmGen script...

HmmGen error code: 1

HmmGen 2.25 (September 27, 2021)
==================================================
Options used:

/tmp/kangm/nhmmer.table /home/kangm/SigmoID/new/CH1.gb /tmp/kangm/GenomeScanOut -d -S 9 -i -b 50 -L 21 -n -f protein_bind -q bound_moiety#OmpR inference#profile:nhmmer:3.1b2 
Only first contig will be processed.

--------------------------------------------------
CONTIG: NC_006348.1

   FEATURES ADDED: 

Traceback (most recent call last):
  File "/home/kangm/SigmoID/SigmoID Resources/HmmGen.py", line 522, in <module>
    my_feature = MySeqFeature(
                 ^^^^^^^^^^^^^
TypeError: SeqFeature.__init__() got an unexpected keyword argument 'strand'

HmmGen command line was: /home/kangm/anaconda3/bin/python /home/kangm/SigmoID/SigmoID\ Resources/HmmGen.py /tmp/kangm/nhmmer.table /home/kangm/SigmoID/new/CH1.gb /tmp/kangm/GenomeScanOut -d -S 9 -i -b 50 -L 21 -n -f protein_bind -q "bound_moiety"#"OmpR" "inference"#"profile:nhmmer:3.1b2"

Genome scan interrupted due to HmmGen.py script error

TermGen 1.18 (August 25, 2021)
==================================================
Options used:
/home/kangm/SigmoID/new/CH1.gb /home/kangm/SigmoID/CH1/CH1_term.gb -C 76 

Creating .fasta file...
Creating .ptt file...
Running TransTerm HP...
--------------------------------------------------
Traceback (most recent call last):
  File "/home/kangm/SigmoID/SigmoID Resources/TermGen.py", line 379, in <module>
    my_feature = SeqFeature(location=feature_location, type='regulatory', strand=strand,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TermGen command line was: /home/kangm/anaconda3/bin/python /home/kangm/SigmoID/SigmoID\ Resources/TermGen.py /home/kangm/SigmoID/new/CH1.gb /home/kangm/SigmoID/CH1/CH1_term.gb  -C 76

Checking python and scripts... 
Python 3.11.7 with Biopython 1.83
HmmGen 2.25 (September 27, 2021)
RepeatGen 1.3 (April 6, 2021)
MastGen 1.13 (September 27, 2020)
TermGen 1.18 (August 25, 2021)
OperOn 1.15 (September 27, 2020)
Genbank to PTT converter 1.21 (August 25, 2021)

Checking command line programs...
nhmmer 3.1b2 (February 2015)
hmmbuild 3.1b2 (February 2015)
alimask  3.1b2 (February 2015)
TransTermHP v2.08 (built on Nov 25 2015)
meme 5.5.5
mast 4.10.2
tomtom 5.5.5
MeShClust 1.2.0 compiled on Mar  5 2019 12:52:18 with OpenMP 201307
tfastx 36.3.8c Nov, 2015
NCBI Edirect 21.8

16 CPU cores detected. All of them can be used for running MEME.
The current setting is to use 8 cores. The number can be changed in the preferences window.

Load alignment or genome file to start.
Please enter your e-mail address in the preferences. It is required for some NCBI services.
No MPICH: 'string

**Comment by p-vychik** [comment]
Hi! 
This is known issue related to changes in the constructor of SeqFeature class starting from BioPython v1.82.
I would suggest the temporary solution - downgrade to BioPython v1.81:

1. delete existing BioPython:
pip remove biopython
2. install 1.81 version:
pip install biopython==1.81

Please let me know if the problem persists
